# example: https://www.phcomp.co.uk/Tutorials/Web-Technologies/example.cnf.txt

[req]
default_bits       = 4096
prompt             = no
default_md         = sha256
distinguished_name = dn
req_extensions     = req_ext

[dn]
countryName             = CA
stateOrProvinceName     = Québec
localityName            = Montréal
organizationName        = Rinkhals
organizationalUnitName  = Rinhals Dev
commonName              = Rinkhals CA
emailAddress            = rinkhals@local.host

[req_ext]
subjectAltName = @alt_names

[alt_names]
DNS.1 = localhost
DNS.2 = rinkhals.local
DNS.3 = *.rinkhals.local
